import { Inter } from 'next/font/google'
import './app.scss';

import StyledComponentsRegistry from '../lib/AntdRegistry';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <body className={inter.className}>
        <div className="App">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>

        </div>
      </body>
    </html>
  )
}
